allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

tasks.register("assembleRelease") {
    dependsOn(":app:assembleRelease")
}

tasks.register("assembleDebug") {
    dependsOn(":app:assembleDebug")
}

tasks.register("assemble") {
    dependsOn(":app:assemble")
}

tasks.register("packageDebug") {
    dependsOn(":app:packageDebug")
}

tasks.register("packageRelease") {
    dependsOn(":app:packageRelease")
}
